### ISSUE TITLE
Level structuur ontwerpen

### ISSUE THREAD

**Issue by ikarago** [Bdahir/Groep3-StressReliefgame-#4]
Er zal een levelstructuur moeten worden ontworpen die de verhaallijn van de game zal vertellen en duidelijk zal moeten maken wat de keuzes voor invloed gaan hebben op het volgende level.

**Comment by ikarago** [comment]
**Concept storyboard**

![IMG_20191030_135817](https://user-images.githubusercontent.com/19528662/67860607-90e49180-fb1e-11e9-8823-aac2dc6e72ce.jpg)

**Comment by rickdsec** [comment]
![afbeelding](https://user-images.githubusercontent.com/57140404/67864757-6a2a5900-fb26-11e9-83d6-7f9185d70f21.png)
